Don't commit empty files

diff --git a/.github/workflows/qa-cleanup.yaml b/.github/workflows/qa-cleanup.yaml
--- a/.github/workflows/qa-cleanup.yaml
+++ b/.github/workflows/qa-cleanup.yaml
@@ -90,14 +90,19 @@ jobs:
 
           ./qa_apps.sh remove
 
-          git config user.name github-actions
-          git config user.email github-actions@github.com
-          git add . && git diff --cached --quiet || \
-            git commit -m "[ci] Cleanup PR-${{ github.event.number }} from ${{ github.repository }}" && \
-            git push && \
-            git status --porcelain
-          
-          echo "QA file has been updated and pushed."
+          if { [ -f "${QA_FILE}" -a -s "${QA_FILE}" ] || [ ! -f "${QA_FILE}" ]; } && [ -s "qa_lanes.libsonnet" ]; then
+            git config user.name github-actions
+            git config user.email github-actions@github.com
+            git add . && git diff --cached --quiet || \
+              git commit -m "[ci] Cleanup PR-${{ github.event.number }} from ${{ github.repository }}" && \
+              git push && \
+              git status --porcelain
+            
+            echo "QA file has been updated and pushed."
+          else
+            echo "${QA_FILE} or qa_lanes.libsonnet is empty. Aborting job."
+            exit 1
+          fi
       
       - name: Release QA Environment
         id: release-qa-env
diff --git a/.github/workflows/update-defaults.yaml b/.github/workflows/update-defaults.yaml
--- a/.github/workflows/update-defaults.yaml
+++ b/.github/workflows/update-defaults.yaml
@@ -54,14 +54,21 @@ jobs:
         run: |-
           cd ${GITHUB_WORKSPACE}/infrastructure/qa-envs
           ./qa_apps.sh update_default
-          
-          git config user.name github-actions
-          git config user.email github-actions@github.com
-          git diff --quiet || \
-            git add defaults.json && \
-            git diff --cached && \
-            git commit -m "[ci] Update default image tag for ${APP_NAME} from ${{ github.repository }}" && \
-            git push && \
-            git status --porcelain
 
-          echo "Default has been updated and pushed."
+          if [ -s "defaults.json" ]; then
+            git config user.name github-actions
+            git config user.email github-actions@github.com
+            git diff --quiet || \
+              git add defaults.json && \
+              git diff --cached && \
+              git commit -m "[ci] Update default image tag for ${APP_NAME} from ${{ github.repository }}" && \
+              git push && \
+              git status --porcelain
+
+            echo "Default has been updated and pushed."
+          else
+            echo "defaults.json is empty. Aborting job."
+            exit 1
+          fi
+          
+          
